// <auto-generated />
using System;
using Gauge.Ingest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gauge.Ingest.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260918142807_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.20");

            modelBuilder.Entity("Gauge.Ingest.Domain.DirtyHour", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HourStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeaseUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("MeterId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MeterId", "HourStart")
                        .IsUnique();

                    b.ToTable("DirtyHours");
                });

            modelBuilder.Entity("Gauge.Ingest.Domain.HourlyAggregate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HourStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("MeterId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalKwh")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MeterId", "HourStart")
                        .IsUnique();

                    b.ToTable("HourlyAggregates");
                });

            modelBuilder.Entity("Gauge.Ingest.Domain.Meter", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Meters");
                });

            modelBuilder.Entity("Gauge.Ingest.Domain.ProcessedBatch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Accepted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rejected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "BatchId")
                        .IsUnique();

                    b.HasIndex("TenantId", "CreatedAt");

                    b.ToTable("ProcessedBatches");
                });

            modelBuilder.Entity("Gauge.Ingest.Domain.Reading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Kwh")
                        .HasColumnType("TEXT");

                    b.Property<string>("MeterId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MeterId", "Timestamp");

                    b.ToTable("Readings");
                });

            modelBuilder.Entity("Gauge.Ingest.Domain.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApiKey")
                        .IsUnique();

                    b.ToTable("Tenants");
                });
#pragma warning restore 612, 618
        }
    }
}
